### ISSUE TITLE
comfy-qr-conditional-interrupt not exist

### ISSUE THREAD

**Issue by b8kings0ga** [coreyryanhanson/comfy-qr#2]

**Comment by coreyryanhanson** [comment]
How did you get that error specifically? Was it when using one of the templates? If so, let me know which one caused it. I think it's probably a remnant from an earlier version with broken compatibility.

**Comment by tukloheshi** [comment]
same 
![Screenshot 2024-02-25 012358](https://github.com/coreyryanhanson/ComfyQR/assets/161191515/31673e5e-e6c8-4904-b3ce-bff363ee61fd)

**Comment by coreyryanhanson** [comment]
Ah I see where it's from. Those images were generated much earlier on. Was concerned about possible repository bloat by replacing image files. I just dug in and updated only the metadata to fix the broken links. After all of this time and many changes to ComfyUI, it appears that rerendering now creates minute differences that won't make it be a 1:1. But it will be extremely close.

In the case of the node in question, I just ended up removing it entirely. All it was was an extra validation step that would interrupt the generation, if it did not meet certain conditions. While handy, I decided to drop that node completely because its functionality would be better suited to a more general set of nodes. Including it in a repository specific to QR codes would be recreating the wheel unnecessarily and adding to bloat.
